### PR TITLE
Use verification and anonymization rules to generated a csv with new data

### PR DESCRIPTION
**Pull request by HenryJulienDesgranges**

### CODE REVIEW

**Comment by CHARLONCyril** [comment]
@HenryJulienDesgranges i saw that you create a function "isInt" can you use it for the rule "BeAnAge" before merge please ?

**Review by CHARLONCyril — COMMENTED** [review]
see my note below

**Comment by HenryJulienDesgranges** [comment]
@CHARLONCyril  ok i will do it rigth now :)

**Comment by CHARLONCyril** [comment]
ok txt @HenryJulienDesgranges good work

**Pull request merged**
