### PR TITLE
Use Univocity to parse CSV file and file librairy to access to a file

### PR DESCRIPTION
**Pull request by CHARLONCyril**
I don't created jUnit test because because both Univocity and File are external librairies

### CODE REVIEW

**Review by HenryJulienDesgranges — CHANGES_REQUESTED** [review]
You have to rework the way to store field and line delimitter and add preconditions to ensure the quality of data

**Comment by HenryJulienDesgranges** [comment]
@HenryJulienDesgranges  can you check again the PR, i added the differents modifications

**Comment by CHARLONCyril** [comment]
@HenryJulienDesgranges Can you please check again the PR, i added the following modifcations

**Comment by HenryJulienDesgranges** [comment]
Hello @CHARLONCyril  everything seems okey, i merge the branch

**Comment by CHARLONCyril** [comment]
can you validate my last changement @HenryJulienDesgranges

**Pull request merged**
